# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models


class StockRequestOrder(models.Model):
    _inherit = "stock.request.order"

    procurement_group_id = fields.Many2one(
        "procurement.group",
        "Procurement Group",
        readonly=True,
        states={"draft": [("readonly", False)]},
        copy=False,
        help="Moves created through this stock request will be put in this "
        "procurement group. If none is given, the moves generated by "
        "procurement rules will be grouped into one big picking.",
    )

    @api.model
    def create(self, vals):
        res = super().create(vals)
        if not res.procurement_group_id:
            procurement_group_id = res._create_procurement_group(res.name)
            res.procurement_group_id = (
                procurement_group_id and procurement_group_id.id or False
            )
            for line in res.stock_request_ids:
                line.procurement_group_id = (
                    procurement_group_id and procurement_group_id.id or False
                )
        return res

    def _create_procurement_group(self, name):
        procurement_group = self.env["procurement.group"].create(
            {
                "name": name,
                "partner_id": self.requested_by.partner_id.id,
            }
        )
        return procurement_group
